services:
  - type: web
    name: thanayaura-gateway-1
    env: python
    plan: starter
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MODEL_DEFAULT_OPENAI
        value: gpt-5
      - key: MODEL_DEFAULT_GEMINI
        value: gemini-2.0-pro
    healthCheckPath: /healthz
